const Noticieros = [
    {
        id: '1',
        titulo: 'Satélite Chasqui I',
        imagen: 'noticia-chasqui1sat',
        noticia: 'Chasqui 1 (en quechua, «correo, mensajero en el Incario») Chasqui I es un proyecto de satélite de un kilogramo de finales de la década del 2000, que fue lanzado con la mano durante una caminata espacial el 18 de agosto de 2014, frente a la Estación Espacial Internacional. El satélite fue diseñado para ser equipado con dos cámaras, una de luz visible y una infrarroja, lo que podría tomar fotos de la Tierra.',
        imagen1: 'noticia-chasqui1sat1',
        imagen2: 'noticia-chasqui1sat2',
        imagen3: 'noticia-chasqui1sat3',
        imagen4: 'noticia-chasqui1sat4',
        imagen5: 'noticia-chasqui1sat5',
        imagen6: 'noticia-chasqui1sat6'
    },  

    {
        id: '2',
        titulo: 'Satélite PerúSAT',
        imagen: 'noticia-perusat',
        noticia: 'PeruSat-1 es un satélite de observación terrestre de propiedad del gobierno peruano el cual es operado por su agencia espacial CONIDA, entidad adscrita al Ministerio de Defensa. Fue construido en Francia por la empresa Airbus Defence & Space4​ y se encuentra operando desde el año 2016.',
        imagen1: 'noticia-perusat1',
        imagen2: 'noticia-perusat2',
        imagen3: 'noticia-perusat3',
        imagen4: 'noticia-perusat4',
        imagen5: 'noticia-perusat5',
        imagen6: 'noticia-perusat6',
    },

    {
        id: '3',
        titulo: 'Satélite PucpSAT',
        imagen: 'noticia-pucpsat',
        noticia: 'El PUCP SAT 1 es un pequeño satélite peruano, lanzado junto con el Pocket PUCP el 21 de noviembre de 2013 desde la plataforma de Yasny, Rusia. Este satélite fue construido por el Instituto de Radioastronomía de la Pontificia Universidad Católica del Perú con un costo cerca de 100 mil dólares. Con este satélite, el Perú ingresó a la Era Espacial.' ,
        imagen1: 'noticia-pucpsat1',
        imagen2: 'noticia-pucpsat2',
        imagen3: 'noticia-pucpsat3',
        imagen4: 'noticia-pucpsat4',
        imagen5: 'noticia-pucpsat5',
        imagen6: 'noticia-pucpsat6',
    },

    {
        id: '4',
        titulo: 'Satélite UapSAT',
        imagen: 'noticia-uapsat',
        noticia: 'UAPSAT 1 es un satélite peruano lanzado el 9 de enero del 2014. Su misión es recolectar información sobre el clima en el espacio. El proyecto fue realizado por los estudiantes y catedráticos de la Universidad Alas Peruanas y tuvo un costo de 160 mil dólares. Para ponerlo en órbita se utilizó el cohete "Antares" lanzado desde el centro de lanzamiento espacial wallops, ubicado en el Estado de Virginia, Estados Unidos.',
        imagen1: 'noticia-uapsat1',
        imagen2: 'noticia-uapsat2',
        imagen3: 'noticia-uapsat3',
        imagen4: 'noticia-uapsat4',
        imagen5: 'noticia-uapsat5',
        imagen6: 'noticia-uapsat6',
    },

    {
        id: '5',
        titulo: 'Satélite PucpSAT',
        imagen: 'noticia-pucpsat',
        noticia: 'El PUCP SAT 1 es un pequeño satélite peruano, lanzado junto con el Pocket PUCP el 21 de noviembre de 2013 desde la plataforma de Yasny, Rusia. Este satélite fue construido por el Instituto de Radioastronomía de la Pontificia Universidad Católica del Perú con un costo cerca de 100 mil dólares. Con este satélite, el Perú ingresó a la Era Espacial.',
        imagen1: 'noticia-pucpsat1',
        imagen2: 'noticia-pucpsat2',
        imagen3: 'noticia-pucpsat3',
        imagen4: 'noticia-pucpsat4',
        imagen5: 'noticia-pucpsat5',
        imagen6: 'noticia-pucpsat6',
    },

    {
        id: '6',
        titulo: 'Satélite UapSAT',
        imagen: 'noticia-uapsat',
        noticia: 'UAPSAT 1 es un satélite peruano lanzado el 9 de enero del 2014. Su misión es recolectar información sobre el clima en el espacio. El proyecto fue realizado por los estudiantes y catedráticos de la Universidad Alas Peruanas y tuvo un costo de 160 mil dólares. Para ponerlo en órbita se utilizó el cohete "Antares" lanzado desde el centro de lanzamiento espacial wallops, ubicado en el Estado de Virginia, Estados Unidos.',
        imagen1: 'noticia-uapsat1',
        imagen2: 'noticia-uapsat2',
        imagen3: 'noticia-uapsat3',
        imagen4: 'noticia-uapsat4',
        imagen5: 'noticia-uapsat5',
        imagen6: 'noticia-uapsat6',
    },

    {
        id: '7',
        titulo: 'Satélite Chasqui I',
        imagen: 'noticia-chasqui1sat',
        noticia: 'Chasqui 1 (en quechua, «correo, mensajero en el Incario») Chasqui I es un proyecto de satélite de un kilogramo de finales de la década del 2000, que fue lanzado con la mano durante una caminata espacial el 18 de agosto de 2014, frente a la Estación Espacial Internacional. El satélite fue diseñado para ser equipado con dos cámaras, una de luz visible y una infrarroja, lo que podría tomar fotos de la Tierra.',
        imagen1: 'noticia-chasqui1sat1',
        imagen2: 'noticia-chasqui1sat2',
        imagen3: 'noticia-chasqui1sat3',
        imagen4: 'noticia-chasqui1sat4',
        imagen5: 'noticia-chasqui1sat5',
        imagen6: 'noticia-chasqui1sat6',
    },
    {
        id: '8',
        titulo: 'Satélite PerúSAT',
        imagen: 'noticia-perusat',
        noticia: 'PeruSat-1 es un satélite de observación terrestre de propiedad del gobierno peruano el cual es operado por su agencia espacial CONIDA, entidad adscrita al Ministerio de Defensa. Fue construido en Francia por la empresa Airbus Defence & Space4​ y se encuentra operando desde el año 2016.',
        imagen1: 'noticia-perusat1',
        imagen2: 'noticia-perusat2',
        imagen3: 'noticia-perusat3',
        imagen4: 'noticia-perusat4',
        imagen5: 'noticia-perusat5',
        imagen6: 'noticia-perusat6',
    },
    {
        id: '9',
        titulo: 'Satélite PucpSAT',
        imagen: 'noticia-pucpsat',
        noticia: 'El PUCP SAT 1 es un pequeño satélite peruano, lanzado junto con el Pocket PUCP el 21 de noviembre de 2013 desde la plataforma de Yasny, Rusia. Este satélite fue construido por el Instituto de Radioastronomía de la Pontificia Universidad Católica del Perú con un costo cerca de 100 mil dólares. Con este satélite, el Perú ingresó a la Era Espacial.' ,
        imagen1: 'noticia-pucpsat1',
        imagen2: 'noticia-pucpsat2',
        imagen3: 'noticia-pucpsat3',
        imagen4: 'noticia-pucpsat4',
        imagen5: 'noticia-pucpsat5',
        imagen6: 'noticia-pucpsat6',
    },
    {
        id: '10',
        titulo: 'Satélite UapSAT',
        imagen: 'noticia-uapsat',
        noticia: 'UAPSAT 1 es un satélite peruano lanzado el 9 de enero del 2014. Su misión es recolectar información sobre el clima en el espacio. El proyecto fue realizado por los estudiantes y catedráticos de la Universidad Alas Peruanas y tuvo un costo de 160 mil dólares. Para ponerlo en órbita se utilizó el cohete "Antares" lanzado desde el centro de lanzamiento espacial wallops, ubicado en el Estado de Virginia, Estados Unidos.',
        imagen1: 'noticia-uapsat1',
        imagen2: 'noticia-uapsat2',
        imagen3: 'noticia-uapsat3',
        imagen4: 'noticia-uapsat4',
        imagen5: 'noticia-uapsat5',
        imagen6: 'noticia-uapsat6',
    },

    {
        id: '11',
        titulo: 'Satélite PucpSAT',
        imagen: 'noticia-pucpsat',
        noticia: 'El PUCP SAT 1 es un pequeño satélite peruano, lanzado junto con el Pocket PUCP el 21 de noviembre de 2013 desde la plataforma de Yasny, Rusia. Este satélite fue construido por el Instituto de Radioastronomía de la Pontificia Universidad Católica del Perú con un costo cerca de 100 mil dólares. Con este satélite, el Perú ingresó a la Era Espacial.' ,
        imagen1: 'noticia-pucpsat1',
        imagen2: 'noticia-pucpsat2',
        imagen3: 'noticia-pucpsat3',
        imagen4: 'noticia-pucpsat4',
        imagen5: 'noticia-pucpsat5',
        imagen6: 'noticia-pucpsat6',
    },
    {
        id: '12',
        titulo: 'Satélite Chasqui I',
        imagen: 'noticia-chasqui1sat',
        noticia: 'Chasqui 1 (en quechua, «correo, mensajero en el Incario») Chasqui I es un proyecto de satélite de un kilogramo de finales de la década del 2000, que fue lanzado con la mano durante una caminata espacial el 18 de agosto de 2014, frente a la Estación Espacial Internacional. El satélite fue diseñado para ser equipado con dos cámaras, una de luz visible y una infrarroja, lo que podría tomar fotos de la Tierra.',
        imagen1: 'noticia-chasqui1sat1',
        imagen2: 'noticia-chasqui1sat2',
        imagen3: 'noticia-chasqui1sat3',
        imagen4: 'noticia-chasqui1sat4',
        imagen5: 'noticia-chasqui1sat5',
        imagen6: 'noticia-chasqui1sat6',
    },
    {
        id: '13',
        titulo: 'Satélite PerúSAT',
        imagen: 'noticia-perusat',
        noticia: 'PeruSat-1 es un satélite de observación terrestre de propiedad del gobierno peruano el cual es operado por su agencia espacial CONIDA, entidad adscrita al Ministerio de Defensa. Fue construido en Francia por la empresa Airbus Defence & Space4​ y se encuentra operando desde el año 2016.',
        imagen1: 'noticia-perusat1',
        imagen2: 'noticia-perusat2',
        imagen3: 'noticia-perusat3',
        imagen4: 'noticia-perusat4',
        imagen5: 'noticia-perusat5',
        imagen6: 'noticia-perusat6',
    },
    {
        id: '14',
        titulo: 'Satélite PucpSAT',
        imagen: 'noticia-pucpsat',
        noticia: 'El PUCP SAT 1 es un pequeño satélite peruano, lanzado junto con el Pocket PUCP el 21 de noviembre de 2013 desde la plataforma de Yasny, Rusia. Este satélite fue construido por el Instituto de Radioastronomía de la Pontificia Universidad Católica del Perú con un costo cerca de 100 mil dólares. Con este satélite, el Perú ingresó a la Era Espacial.' ,
        imagen1: 'noticia-pucpsat1',
        imagen2: 'noticia-pucpsat2',
        imagen3: 'noticia-pucpsat3',
        imagen4: 'noticia-pucpsat4',
        imagen5: 'noticia-pucpsat5',
        imagen6: 'noticia-pucpsat6',
    },
    {
        id: '15',
        titulo: 'Satélite UapSAT',
        imagen: 'noticia-uapsat',
        noticia: 'UAPSAT 1 es un satélite peruano lanzado el 9 de enero del 2014. Su misión es recolectar información sobre el clima en el espacio. El proyecto fue realizado por los estudiantes y catedráticos de la Universidad Alas Peruanas y tuvo un costo de 160 mil dólares. Para ponerlo en órbita se utilizó el cohete "Antares" lanzado desde el centro de lanzamiento espacial wallops, ubicado en el Estado de Virginia, Estados Unidos.',
        imagen1: 'noticia-uapsat1',
        imagen2: 'noticia-uapsat2',
        imagen3: 'noticia-uapsat3',
        imagen4: 'noticia-uapsat4',
        imagen5: 'noticia-uapsat5',
        imagen6: 'noticia-uapsat6',
    },
    {
        id: '16',
        titulo: 'Satélite Chasqui I',
        imagen: 'noticia-chasqui1sat',
        noticia: 'Chasqui 1 (en quechua, «correo, mensajero en el Incario») Chasqui I es un proyecto de satélite de un kilogramo de finales de la década del 2000, que fue lanzado con la mano durante una caminata espacial el 18 de agosto de 2014, frente a la Estación Espacial Internacional. El satélite fue diseñado para ser equipado con dos cámaras, una de luz visible y una infrarroja, lo que podría tomar fotos de la Tierra.',
        imagen1: 'noticia-chasqui1sat1',
        imagen2: 'noticia-chasqui1sat2',
        imagen3: 'noticia-chasqui1sat3',
        imagen4: 'noticia-chasqui1sat4',
        imagen5: 'noticia-chasqui1sat5',
        imagen6: 'noticia-chasqui1sat6',
    },
    {
        id: '17',
        titulo: 'Satélite PerúSAT',
        imagen: 'noticia-perusat',
        noticia: 'PeruSat-1 es un satélite de observación terrestre de propiedad del gobierno peruano el cual es operado por su agencia espacial CONIDA, entidad adscrita al Ministerio de Defensa. Fue construido en Francia por la empresa Airbus Defence & Space4​ y se encuentra operando desde el año 2016.',
        imagen1: 'noticia-perusat1',
        imagen2: 'noticia-perusat2',
        imagen3: 'noticia-perusat3',
        imagen4: 'noticia-perusat4',
        imagen5: 'noticia-perusat5',
        imagen6: 'noticia-perusat6',
    },
    {
        id: '18',
        titulo: 'Satélite PucpSAT',
        imagen: 'noticia-pucpsat',
        noticia: 'El PUCP SAT 1 es un pequeño satélite peruano, lanzado junto con el Pocket PUCP el 21 de noviembre de 2013 desde la plataforma de Yasny, Rusia. Este satélite fue construido por el Instituto de Radioastronomía de la Pontificia Universidad Católica del Perú con un costo cerca de 100 mil dólares. Con este satélite, el Perú ingresó a la Era Espacial.' ,
        imagen1: 'noticia-pucpsat1',
        imagen2: 'noticia-pucpsat2',
        imagen3: 'noticia-pucpsat3',
        imagen4: 'noticia-pucpsat4',
        imagen5: 'noticia-pucpsat5',
        imagen6: 'noticia-pucpsat6',
    },
    {
        id: '19',
        titulo: 'Satélite UapSAT',
        imagen: 'noticia-uapsat',
        noticia: 'UAPSAT 1 es un satélite peruano lanzado el 9 de enero del 2014. Su misión es recolectar información sobre el clima en el espacio. El proyecto fue realizado por los estudiantes y catedráticos de la Universidad Alas Peruanas y tuvo un costo de 160 mil dólares. Para ponerlo en órbita se utilizó el cohete "Antares" lanzado desde el centro de lanzamiento espacial wallops, ubicado en el Estado de Virginia, Estados Unidos.',
        imagen1: 'noticia-uapsat1',
        imagen2: 'noticia-uapsat2',
        imagen3: 'noticia-uapsat3',
        imagen4: 'noticia-uapsat4',
        imagen5: 'noticia-uapsat5',
        imagen6: 'noticia-uapsat6',
    },
    {
        id: '20',
        titulo: 'Satélite PerúSAT',
        imagen: 'noticia-perusat',
        noticia: 'PeruSat-1 es un satélite de observación terrestre de propiedad del gobierno peruano el cual es operado por su agencia espacial CONIDA, entidad adscrita al Ministerio de Defensa. Fue construido en Francia por la empresa Airbus Defence & Space4​ y se encuentra operando desde el año 2016.',
        imagen1: 'noticia-perusat1',
        imagen2: 'noticia-perusat2',
        imagen3: 'noticia-perusat3',
        imagen4: 'noticia-perusat4',
        imagen5: 'noticia-perusat5',
        imagen6: 'noticia-perusat6',
    },
    {
        id: '21',
        titulo: 'Satélite Chasqui I',
        imagen: 'noticia-chasqui1sat',
        noticia: 'Chasqui 1 (en quechua, «correo, mensajero en el Incario») Chasqui I es un proyecto de satélite de un kilogramo de finales de la década del 2000, que fue lanzado con la mano durante una caminata espacial el 18 de agosto de 2014, frente a la Estación Espacial Internacional. El satélite fue diseñado para ser equipado con dos cámaras, una de luz visible y una infrarroja, lo que podría tomar fotos de la Tierra.',
        imagen1: 'noticia-chasqui1sat1',
        imagen2: 'noticia-chasqui1sat2',
        imagen3: 'noticia-chasqui1sat3',
        imagen4: 'noticia-chasqui1sat4',
        imagen5: 'noticia-chasqui1sat5',
        imagen6: 'noticia-chasqui1sat6',
    },
    {
        id: '22',
        titulo: 'Satélite PerúSAT',
        imagen: 'noticia-perusat',
        noticia: 'PeruSat-1 es un satélite de observación terrestre de propiedad del gobierno peruano el cual es operado por su agencia espacial CONIDA, entidad adscrita al Ministerio de Defensa. Fue construido en Francia por la empresa Airbus Defence & Space4​ y se encuentra operando desde el año 2016.',
        imagen1: 'noticia-perusat1',
        imagen2: 'noticia-perusat2',
        imagen3: 'noticia-perusat3',
        imagen4: 'noticia-perusat4',
        imagen5: 'noticia-perusat5',
        imagen6: 'noticia-perusat6',
    },
    {
        id: '23',
        titulo: 'Satélite PucpSAT',
        imagen: 'noticia-pucpsat',
        noticia: 'El PUCP SAT 1 es un pequeño satélite peruano, lanzado junto con el Pocket PUCP el 21 de noviembre de 2013 desde la plataforma de Yasny, Rusia. Este satélite fue construido por el Instituto de Radioastronomía de la Pontificia Universidad Católica del Perú con un costo cerca de 100 mil dólares. Con este satélite, el Perú ingresó a la Era Espacial.' ,
        imagen1: 'noticia-pucpsat1',
        imagen2: 'noticia-pucpsat2',
        imagen3: 'noticia-pucpsat3',
        imagen4: 'noticia-pucpsat4',
        imagen5: 'noticia-pucpsat5',
        imagen6: 'noticia-pucpsat6',
    },
    {
        id: '24',
        titulo: 'Satélite UapSAT',
        imagen: 'noticia-uapsat',
        noticia: 'UAPSAT 1 es un satélite peruano lanzado el 9 de enero del 2014. Su misión es recolectar información sobre el clima en el espacio. El proyecto fue realizado por los estudiantes y catedráticos de la Universidad Alas Peruanas y tuvo un costo de 160 mil dólares. Para ponerlo en órbita se utilizó el cohete "Antares" lanzado desde el centro de lanzamiento espacial wallops, ubicado en el Estado de Virginia, Estados Unidos.',
        imagen1: 'noticia-uapsat1',
        imagen2: 'noticia-uapsat2',
        imagen3: 'noticia-uapsat3',
        imagen4: 'noticia-uapsat4',
        imagen5: 'noticia-uapsat5',
        imagen6: 'noticia-uapsat6',
    },
    {
        id: '25',
        titulo: 'Satélite Chasqui I',
        imagen: 'noticia-chasqui1sat',
        noticia: 'Chasqui 1 (en quechua, «correo, mensajero en el Incario») Chasqui I es un proyecto de satélite de un kilogramo de finales de la década del 2000, que fue lanzado con la mano durante una caminata espacial el 18 de agosto de 2014, frente a la Estación Espacial Internacional. El satélite fue diseñado para ser equipado con dos cámaras, una de luz visible y una infrarroja, lo que podría tomar fotos de la Tierra.',
        imagen1: 'noticia-chasqui1sat1',
        imagen2: 'noticia-chasqui1sat2',
        imagen3: 'noticia-chasqui1sat3',
        imagen4: 'noticia-chasqui1sat4',
        imagen5: 'noticia-chasqui1sat5',
        imagen6: 'noticia-chasqui1sat6',
    },
    {
        id: '26',
        titulo: 'Satélite PucpSAT',
        imagen: 'noticia-pucpsat',
        noticia: 'El PUCP SAT 1 es un pequeño satélite peruano, lanzado junto con el Pocket PUCP el 21 de noviembre de 2013 desde la plataforma de Yasny, Rusia. Este satélite fue construido por el Instituto de Radioastronomía de la Pontificia Universidad Católica del Perú con un costo cerca de 100 mil dólares. Con este satélite, el Perú ingresó a la Era Espacial.' ,
        imagen1: 'noticia-pucpsat1',
        imagen2: 'noticia-pucpsat2',
        imagen3: 'noticia-pucpsat3',
        imagen4: 'noticia-pucpsat4',
        imagen5: 'noticia-pucpsat5',
        imagen6: 'noticia-pucpsat6',
    },
]

export default Noticieros;